### ISSUE TITLE
Extremly hard to see highlighted text

### ISSUE THREAD

**Issue by noshitsherlock** [dracula/visual-studio#1]
Love the theme, but when you highlight text in visual studio it is very hard to see what you have actually highlighted.

![image](https://cloud.githubusercontent.com/assets/3532879/23749958/04ea8ce4-04cb-11e7-8b0e-db73b38c6632.png)

Maybe a better solution would be to have the same highlighting as when the window looses focus?

![image](https://cloud.githubusercontent.com/assets/3532879/23749988/29fc86a4-04cb-11e7-89e9-2a6e5217608e.png)

**Comment by zenorocha** [comment]
Thanks for reporting @noshitsherlock!

@epidemicz can you take a look?

**Comment by epidemicz** [comment]
That's a good idea, I will take a look into it.

**Comment by noshitsherlock** [comment]
Looking forward to testing it out :) Awesome job all of you.

**Comment by epidemicz** [comment]
@noshitsherlock can you grab the latest and see how it looks now?  I tried to meet you half way with the selected text, also updated the current line highlight.  

@zenorocha can you give me any pointers on how I can update the website for the visual-studio theme?  I tried following the instructions on https://github.com/dracula/dracula.github.io, but `npm run deploy` doesn't seem to do anything and I currently don't have push access to that repo.  Do I need to submit a pull request?

**Comment by zenorocha** [comment]
Hey @epidemicz, yes please send a pull request, I can run the deploy command after merging it.

**Comment by noshitsherlock** [comment]
@epidemicz That was  really good! Not as bright as my proposal. So I would say that you made it perfect 👍

**Comment by epidemicz** [comment]
@noshitsherlock awesome!  I appreciate the feedback!
