### ISSUE TITLE
Add theme to Color Themes extension for Visual Studio

### ISSUE THREAD

**Issue by justcla** [dracula/visual-studio#11]
Can this theme be bundled with the other free themes in the Visual Studio extension [Color Themes for Visual Studio](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.ColorThemesforVisualStudio&ssr=false#overview) ?

**Comment by zenorocha** [comment]
Hey @epidemicz, would you be able to make this happen?

**Comment by epidemicz** [comment]
@zenorocha Let me take a look and see what I can do.

**Comment by epidemicz** [comment]
Okay, I've sent them a [pull request](https://github.com/microsoft/VS-ColorThemes/pull/92).  

Thanks for the suggestion.

**Comment by zenorocha** [comment]
Thank you for working on those issues @epidemicz!

**Comment by waf** [comment]
My understanding is that the Color Themes in visual studio have two parts:

- Syntax highlighting (this repo)
- GUI elements (menus, toolbars, etc)

Would anyone be interested in themes for the GUI elements? I've created one that I use personally:

![image](https://user-images.githubusercontent.com/97195/82400937-aef5ed00-9a82-11ea-9142-c79519326774.png)

It uses the dracula colors and is a bit muted, so the focus can be mostly on the syntax highlighting. If there's interest, I can make a PR.

**Comment by benjaminsampica** [comment]
@waf I'm looking for this exact thing and am very interested.

**Comment by waf** [comment]
@benjaminsampica I've attached the theme, see the readme inside. [Dracula Visual Studio UI Theme.zip](https://github.com/dracula/visual-studio/files/4672170/Dracula.Visual.Studio.UI.Theme.zip)

@epidemicz I'm happy to turn this into a PR if you'd like. It's one additional file, a `.vstheme` file contains an XML definition.

**Comment by ziilok** [comment]
Great job. I used your theme and fixed some things:

- invisible region symbols (on the left side of page)
- overview 
- SQL colors
- make colors scheme as much as possible as for visual studio code (Methods and Properties colors)
- remove black background when selecting text

[Dracula.zip](https://github.com/dracula/visual-studio/files/4799231/Dracula.zip)

**Comment by byyxx128** [comment]
## The [PR](https://github.com/microsoft/VS-ColorThemes/pull/92) is waiting on author.

![image](https://user-images.githubusercontent.com/20079289/93765448-7be98300-fc47-11ea-958e-d29d984a7964.png)

**Comment by deggen40** [comment]
Will this ever get an official release?

**Comment by jvbs** [comment]
Any chance of being released officially with the color scheme of the text editor?

**Comment by justcla** [comment]
No, there's pretty much no chance any additional themes will be added to Visual Studio's default theme set.

That's why I created the Color Themes extension.

**Comment by jvbs** [comment]
Well... at least should be the official way explained in Dracula's documentation, makes no sense only changing the text editor color scheme tbh.
