### ISSUE TITLE
Error when Importing  settings

### ISSUE THREAD

**Issue by Westfallx** [dracula/visual-studio#14]
Any can help me to resolve this issue?
Your settings were imported, but there were some errors.

Error 1:  TypeScript Specific: Unable to import property 'JsxEmitForLooseFiles' because it contains invalid data '2'.
Error 2:  TypeScript Specific: Unable to import property 'ModuleKindForLooseFiles' because it contains invalid data '0'.

**Comment by luxonauta** [comment]
Hi 👋🏻, in recent updates, these issues have been fixed; thank you for your feedback! 🧛🏻
