### ISSUE TITLE
Punctuation marks incorrect color on latest VS for Mac (8.9, build 1651)

### ISSUE THREAD

**Issue by vga-256** [dracula/visual-studio#16]
Curly braces, parenthesis, periods, plus, minus, colons, semi-colons, equals, and commas now appear as black with VS Mac 8.9.

![Screen Shot 2021-03-02 at 2 12 29 PM](https://user-images.githubusercontent.com/6203391/109715958-7a5ea800-7b61-11eb-8991-3a081fd033ca.png)
![Screen Shot 2021-03-02 at 2 15 05 PM](https://user-images.githubusercontent.com/6203391/109716176-bdb91680-7b61-11eb-828e-2610b3f145ee.png)

**Comment by juavazmor** [comment]
Same problem, I've just upgraded VS to the latest version and found it like that. 

As a workaround, you can edit "dracula.vssettings" with a text editor and change line 78 from this:

`<Item Background="0x02000000" BoldFont="No" Foreground="0x02000000" Name="Operator" />`

to this:

<Item Background="0x02000000" BoldFont="No" Foreground="0x02FFFFFF" Name="Operator" />

But my main concern is that I no longer see the theme to look like it used to... Colours are different now for keywords etc?

**Comment by 256colour** [comment]
That change worked great for me! I don't see any problems with the other colours. 

Thank you.

**Comment by lixianguser** [comment]
Same problem，thank you！

**Comment by j-lord** [comment]
This indeed is the fix for this problem, thanks!

**Comment by RTirumala** [comment]
This worked for me, thanks a lot.

**Comment by carsanwitt** [comment]
> Same problem, I've just upgraded VS to the latest version and found it like that.
> 
> As a workaround, you can edit "dracula.vssettings" with a text editor and change line 78 from this:
> 
> `<Item Background="0x02000000" BoldFont="No" Foreground="0x02000000" Name="Operator" />`
> 
> to this:
> 
> `<Item Background="0x02000000" BoldFont="No" Foreground="0x02FFFFFF" Name="Operator" />`
> 
> But my main concern is that I no longer see the theme to look like it used to... Are colours different now (for keywords etc)?

This change worked for me too!
This should be patched or something by now 😅

**Comment by luxonauta** [comment]
In recent updates, these issues have been fixed; thank you all for your input and feedback! 🚀

![BowCountDraculaGIF](https://user-images.githubusercontent.com/48334856/191021027-e9f946d6-43a1-4ccf-b8e4-4de8bf580e35.gif)
