### ISSUE TITLE
Auto-update of the theme, reset all customization (font name, font size etc)

### ISSUE THREAD

**Issue by pasqualedante** [dracula/visual-studio#18]
I have customized some editor aspect (font, guideline color etc): after the last update all was reverted to default settings.

![image](https://user-images.githubusercontent.com/813690/134495718-0621b854-a2ae-43d6-a604-c1773a4744eb.png)

**Comment by luxonauta** [comment]
We've been investigating, and unfortunately, we cannot replicate your issue. 😥

I believe it is not a problem with the theme itself. Since it is only responsible for changing the IDE's colours, we will be keeping an eye out for possible other reports of the same problem! 💥
