### ISSUE TITLE
Can't see highlighted comment text

### ISSUE THREAD

**Issue by yougotwill** [dracula/visual-studio#2]
Hi, firstly this theme is fantastic 👍 I'm using Visual Studio for Mac 

<img width="1440" alt="screen shot 2017-09-19 at 8 07 45 am" src="https://user-images.githubusercontent.com/14887287/30578075-4a4fe6aa-9d12-11e7-891d-0d09180063e1.png">

As you can see the comment that is highlighted is very difficult to see. I think this happened due to the fix for issue [#1](https://github.com/dracula/visual-studio/issues/1).

**Comment by epidemicz** [comment]
@yougotwill I'm afraid I don't have an easy way to test this on the mac build, as it stand right now I am not able to reproduce on windows.

I believe the setting you want to look for is "**Highlight Current Line**" under Tools > Options > Fonts and Colors.  

If you can find a color that works decent for both, I'd be willing to meet you in the middle -- but that isn't a great solution.

I'd hate to have a separate branch just for mac, but it may come to that,

Thanks for reporting and I'm so sorry I didn't get to this sooner.

**Comment by e-nathan** [comment]
Little offtopic, but @yougotwill can you please help on how you got this theme setup for VS Mac?
