### ISSUE TITLE
Visual Studio 2022 ARM64 support

### ISSUE THREAD

**Issue by joesdu** [dracula/visual-studio#25]
Visual Studio 2022 ARM64 support

**Comment by BradR91** [comment]
Please update for VS 2022 ARM64! :)

**Comment by joesdu** [comment]
just up .Net Framework 4.5 to 4.8.1 ,change the core editor version to 17.4 in the vsixmainfest file and rebuild to support VS2022 ARM64.

**Comment by BradR91** [comment]
> just up .Net Framework 4.5 to 4.8.1 ,change the core editor version to 17.4 in the vsixmainfest file and rebuild to support VS2022 ARM64.

Upped the target framework to 4.8.1 and changed the core editor version to (17.4, 18.0) I've tried to rebuild it after changing the product architecture to arm64 in the install targets but it fails with a build error "schema validation error". 

Not sure if I'm doing something simple wrong, or if I misunderstood what you've said haha, any assistance would be appreciated :P?

**Comment by joesdu** [comment]
> Not sure if I'm doing something simple wrong, or if I misunderstood what you've said haha, any assistance would be appreciated :P?

Is there a liveshare?

**Comment by BradR91** [comment]
> > Not sure if I'm doing something simple wrong, or if I misunderstood what you've said haha, any assistance would be appreciated :P?
> 
> Is there a liveshare? Is there a liveshare? You don't need to add the compiled architecture of AMR64, just add the ARM64 content in the vsixmainfest file, and select anycpu when building

my manifest file this - 

<Installation>
        <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.4, 18.0)">
            <ProductArchitecture>arm64</ProductArchitecture>
        </InstallationTarget>
    </Installation>

build settings set to any cpu

**Comment by joesdu** [comment]
> > > Not sure if I'm doing something simple wrong, or if I misunderstood what you've said haha, any assistance would be appreciated :P?
> > 
> > 
> > Is there a liveshare? Is there a liveshare? You don't need to add the compiled architecture of AMR64, just add the ARM64 content in the vsixmainfest file, and select anycpu when building
> 
> my manifest file has this -
> 
> Installation InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.4, 18.0)" ProductArchitecture arm64 ProductArchitecture InstallationTarget Installation
> 
> build settings set to any cpu
> 
> Sorted it, needed to update VSSDK Build Tools after that it compiled but then it wouldn't install so changed the .net framework in the manifest back to 4.5 and it installed perfectly. Thanks for the help!

Do you have the source code to share with me, I'll try to update ARM4 support.

**Comment by kakaLuoW** [comment]
Visual Studio 2022 ARM64，the color of symbols (such as braces, equal signs, semicolons, etc.) is black, which looks strange<img width="702" alt="image" src="https://user-images.githubusercontent.com/103268638/224551240-300e37a4-0388-4793-9f66-64fd62ab7308.png">

**Comment by azgcloudev** [comment]
I have the same issue symbols looks the same in a ARM based macbook air

<img width="930" alt="image" src="https://github.com/dracula/visual-studio/assets/72358828/df2aaeff-02aa-4729-92f4-f7abcd3dd40b">
