### ISSUE TITLE
Visual Studio for Mac 

### ISSUE THREAD

**Issue by BradR91** [dracula/visual-studio#26]
When importing vss settings file to VS for Mac 2022, the braces, semi colons, periods etc are appearing in black which makes them quite tough to read. Does anyone know what to change in the vss settings file to have them appear white instead? 

Image of the editor - https://ibb.co/pJJ0Vnw

**Comment by mintiefresh** [comment]
I'm having the same issues here with VS for Mac 2022.

**Comment by BradR91** [comment]
duplicate issue
