### ISSUE TITLE
The color scheme seems to be different from your screenshot.

### ISSUE THREAD

**Issue by kjgfcdb** [dracula/visual-studio#3]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

Hi, thank you for making such a awesome color theme for visual studio. Recently I started to use visual studio 2017 community for coding. But after importing the settings you provide, I found that the **color seems  to be different from your sceenshot**. Like this.
![scshot](https://user-images.githubusercontent.com/15307944/30974779-186cbf80-a4a3-11e7-9ccd-b94ad0c466f7.png)

So I want to know if there are any problems with the settings?  Thank you!

**Comment by kjgfcdb** [comment]
@konafa Thank you so much! This issue is successfully fixed.

**Comment by kjgfcdb** [comment]
@konafa Thank you so much! This issue is successfully fixed.

**Comment by konafa** [comment]
Glad it helped. Dracula is one of my favourite themes. Happy (dark) coding 💻

**Comment by zenorocha** [comment]
Hey @konafa, thanks for helping out!

Are you interested in becoming part of the Dracula theme for Visual Studio?

**Comment by konafa** [comment]
Sure @zenorocha, happy to contribute. Thank you (and @epidemicz) for sharing your beautiful work.

**Comment by zenorocha** [comment]
You should have received the invite now @konafa!

Feel free to merge and address open PRs/issues ;)

**Comment by konafa** [comment]
Cheers!

**Comment by pagangil** [comment]
Thanks for creating such an awesome theme. One thing I noticed was that the Visual studio code theme is much colorful as compared to Visual studio theme. Is the Visual studio theme work in progress or is it the final product?

**Comment by konafa** [comment]
Hi @pagangil , happy to look into that. Could you please post a screenshot to help clarify what you mean and specify the programming language you're using. Also, please do so in a [new issue](https://github.com/dracula/visual-studio/issues) thread, as this one is closed. Thanks!
