### ISSUE TITLE
Dracula Theme cannot be installed on Visual Studio 2022 on ARM64.

### ISSUE THREAD

**Issue by josteink** [dracula/visual-studio#30]
Windows 11 and Visual Studio 2022 now come in native ARM64 versions, which are popular in VMs on "Apple Silicon" MacBooks and Mac minis.

![image](https://github.com/dracula/visual-studio/assets/411338/88ac69b0-8650-43fa-b452-e91c35e4cf5a)

When trying to install Dracula in such an environment you get the following error:

![image](https://github.com/dracula/visual-studio/assets/411338/c80adc9a-acb7-477b-9435-fa5ab26c156f)

I'm no VSIX export, but unless the theme contains native code, I'm going to assume this fails for no other reason than the VSIX manifest saying that it supports AMD64 only :)

![image](https://github.com/dracula/visual-studio/assets/411338/d5357333-8894-4ca2-b9f3-f9851e972b1b)

Can someone update the VSIX and get ARM64 in there too? :)

**Comment by josteink** [comment]
Editing the manifest file directly and replacing AMD64 with ARM64, I get this instead:

![image](https://github.com/dracula/visual-studio/assets/411338/9421f250-47c7-4bf7-8d49-7df44d262f23)

And after that installation actually succeeds 😄

**Comment by wbpayne22902** [comment]
I can verify this solution works on Visual Studio ARM64 17.7.6.

**Comment by josteink** [comment]
I've added a PR to address this. Would be nice if someone could go mergey on it :)

**Comment by luxonauta** [comment]
https://github.com/dracula/visual-studio/pull/32
