### ISSUE TITLE
VS2019 Compatibility (and consider adding to VS-ColorThemes)

### ISSUE THREAD

**Issue by mzhukovs** [dracula/visual-studio#7]
By far my favorite theme. Thanks to all contributors for this one...
2 quick things:
1. Didn't see an option to download the theme from your website for VS2019 (currently in preview). Will you be releasing an extension soon?
2. You guys should consider adding this as a theme to the "Color Themes for Visual Studio" extension, if possible: [https://github.com/Microsoft/VS-ColorThemes](https://github.com/Microsoft/VS-ColorThemes)

**Comment by byyxx128** [comment]
Support this. But no one here?

**Comment by konafa** [comment]
Hi @mzhukovs;
1. The same theme already works in VS2017 or VS2019. Maybe @zenorocha could change the [website](https://draculatheme.com/visual-studio/)'s "Install manually" section to say 2017/2019 for now.
2. The "Color Themes for Visual Studio" requires signing a license agreement, so I'd defer that to @zenorocha / @epidemicz . Also, see the FAQ regarding UI themes in general: https://github.com/dracula/dracula-theme#do-you-accept-ui-themes

**Comment by mzhukovs** [comment]
Thanks @konafa  - yep been using it just fine  :)  
One thing for your consideration though that is VS2019 specific - there is now a "**Keyword - Control**" display item that can be customized separately from the regular "Keyword" - may want to come up with a separate color for that (or not).

**Comment by byyxx128** [comment]
We basically expect it can be published on the marketplace.
https://marketplace.visualstudio.com/vs
Then we can easily install directly rather than importing manually.
And this extension will be helpful to modify themes.
https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2019ColorThemeEditor
It seems there are much fewer maintainers than VS Code.

**Comment by mzhukovs** [comment]
I made 2 .vsthemes that ppl can easily import if they wish:

Here is one that focuses mainly on the editor (note I added a few things that I personally like, e.g. method names highlighted in yellow and then the strings/URLs are orange instead of yellow now, also made operators red, all using the color palette still as posted on your github page, see screenshot below):
https://gist.github.com/mzhukovs/8f62b5e7f01d1c0ba1207a70de20e2d3

![image](https://user-images.githubusercontent.com/13161978/59560132-423acd00-903f-11e9-9723-74235f2b2d5f.png)


Here is one that has a lot more IDE color changes too:
https://gist.github.com/mzhukovs/438f4798cef3caf61549892331fbb544

**Comment by epidemicz** [comment]
Thanks to the user that mentioned that it should work with 2019 out of the box.  I'll look into updating the website to clarify - thanks very much.

See #11 regarding adding the theme to "Color Themes for Visual Studio" - thanks again for the suggesteion.
