### ISSUE TITLE
Dark Theme Getting Overwritten

### ISSUE THREAD

**Issue by Sildoreth** [dracula/visual-studio#9]
I am finding it impossible to simply **add** the Dracula theme to Visual Studio. I followed the instructions at [draculatheme.com](https://draculatheme.com/visual-studio/), and now instead of having an additional Dracula theme, I have a Dark theme that has been overwritten with the Dracula colors. I even tried first creating a copy of the Dark theme and setting that as the active theme before importing. But the result was the same. Users should not have to choose between having the Dark theme available or the Dracula theme.

Perhaps the file for changing the Visual Studio theme should be a .vstheme file, not a .vssettings file? Alternatively, perhaps the directions could be updated; though, I don't know how.

**Comment by Sildoreth** [comment]
Removing this line from the vssettings file before importing gave the "correct" behavior of modifying only the current theme instead of targeting the Dark theme.

`<Theme Id="{1DED0138-47CE-435E-84EF-9EC1F439B749}" />`

This at least allows users to create a new theme named "Dracula" and import the settings to that theme.

**Comment by epidemicz** [comment]
Removed the Theme Id, thanks for the heads up!
